### PR TITLE
Add further discussion of PyVO and testing

### PR DESCRIPTION
**Pull request by gpdf**
Also expand discussion of how the API Aspect will be used.

### CODE REVIEW

**Review by SimonKrughoff — APPROVED** [review]
My only comment is that it would be helpful to include a link to taplint.  It seems like this one may work: http://www.star.bris.ac.uk/~mbt/stilts/sun256/taplint.html.

**Comment by gpdf** [comment]
Thanks, good suggestion!  I'll also ask @mbtaylor if he has a publication reference for `taplint`.

**Comment by mbtaylor** [comment]
Thanks for the reference.  The canonical URL for taplint, such as it is, is http://www.starlink.ac.uk/stilts/sun256/taplint.html, which currently and for the forseeable future redirects to the link that  @SimonKrughoff gave above.  Taplint is part of STILTS, and if you want a publication reference for STILTS you can use the paper http://adsabs.harvard.edu/abs/2006ASPC..351..666T or the ASCL entry http://ascl.net/1105.001

**Comment by gpdf** [comment]
@SimonKrughoff Can you have a look at the latest diff?  I think I've satisfied the request for a citation.  The Travis builds are failing, but that is a problem with `lander` (see #dm-docs) - the LaTeX stage of the build seems to be fine.

**Comment by gpdf** [comment]
I gather @SimonKrughoff is on vacation.  I will go ahead and merge.  There will be more edits to LDM-542 in the future, in which we can address any further refinements.

**Pull request merged**
